[0m15:11:51.416020 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016166813DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000161668129F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016166812E10>]}


============================== 15:11:51.454082 | e8f357d2-999e-49bd-b760-fa1960fb9afc ==============================
[0m15:11:51.454082 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:11:51.457334 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\abhishek.karmakar_s2\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:11:56.092288 [debug] [MainThread]: Starter project path: C:\Users\abhishek.karmakar_s2\dbt-files\dbt-env\Lib\site-packages\dbt\include\starter_project
[0m15:11:56.157412 [info ] [MainThread]: 
Your new dbt project "assignment" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:11:56.157412 [info ] [MainThread]: Setting up your profile.
[0m15:12:48.242509 [info ] [MainThread]: Profile assignment written to C:\Users\abhishek.karmakar_s2\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:12:48.249942 [debug] [MainThread]: Command `dbt init` succeeded at 15:12:48.249942 after 57.15 seconds
[0m15:12:48.251463 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016166811460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016166812E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016163BEBFB0>]}
[0m15:12:48.251463 [debug] [MainThread]: Flushing usage events
[0m15:12:49.538175 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:15:12.657381 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027505810170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027505811A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000275058117F0>]}


============================== 15:15:12.660147 | 786f2bc0-759b-42b3-9cac-630aaf5929be ==============================
[0m15:15:12.660147 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:15:12.660147 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\abhishek.karmakar_s2\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:15:49.307495 [debug] [MainThread]: Starter project path: C:\Users\abhishek.karmakar_s2\dbt-files\dbt-env\Lib\site-packages\dbt\include\starter_project
[0m15:15:49.351303 [info ] [MainThread]: 
Your new dbt project "dbt_assignment" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:15:49.354125 [info ] [MainThread]: Setting up your profile.
[0m15:16:13.004505 [info ] [MainThread]: Profile dbt_assignment written to C:\Users\abhishek.karmakar_s2\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:16:13.008164 [debug] [MainThread]: Command `dbt init` succeeded at 15:16:13.008164 after 60.71 seconds
[0m15:16:13.009171 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027500BADB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000275058C8140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027505908DD0>]}
[0m15:16:13.010649 [debug] [MainThread]: Flushing usage events
[0m15:16:13.911783 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:16:52.354635 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B803410710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B803412F60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B803412AE0>]}


============================== 15:16:52.361574 | b7f2b6ef-2cdd-4c1d-8f0e-93193a56f44a ==============================
[0m15:16:52.361574 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:16:52.361574 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\abhishek.karmakar_s2\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt test', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:16:52.361574 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\abhishek.karmakar_s2\dbt-files\GitHub\assignment\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:16:52.365015 [debug] [MainThread]: Command `dbt test` failed at 15:16:52.365015 after 0.25 seconds
[0m15:16:52.365015 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B8030D5E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B803433FB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B801E04B30>]}
[0m15:16:52.365015 [debug] [MainThread]: Flushing usage events
[0m15:16:53.354953 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:17:43.217764 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF3DA9EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF13813D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF33FB8F0>]}


============================== 15:17:43.224150 | f9783979-9dd2-4d9d-9cd1-aada57d2e977 ==============================
[0m15:17:43.224150 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:17:43.224150 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\abhishek.karmakar_s2\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m15:17:43.281276 [info ] [MainThread]: dbt version: 1.9.4
[0m15:17:43.282871 [info ] [MainThread]: python version: 3.12.10
[0m15:17:43.282871 [info ] [MainThread]: python path: C:\Users\abhishek.karmakar_s2\dbt-files\dbt-env\Scripts\python.exe
[0m15:17:43.282871 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m15:17:43.387921 [info ] [MainThread]: Using profiles dir at C:\Users\abhishek.karmakar_s2\.dbt
[0m15:17:43.389940 [info ] [MainThread]: Using profiles.yml file at C:\Users\abhishek.karmakar_s2\.dbt\profiles.yml
[0m15:17:43.389940 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\abhishek.karmakar_s2\dbt-files\GitHub\assignment\dbt_project.yml
[0m15:17:43.389940 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:17:43.391956 [debug] [MainThread]: Command `dbt debug` failed at 15:17:43.391956 after 0.45 seconds
[0m15:17:43.393717 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF503FBF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF50DBB00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027EF5188800>]}
[0m15:17:43.393717 [debug] [MainThread]: Flushing usage events
[0m15:17:44.654803 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:18:32.659590 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025376113E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025374B07200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025374C17FB0>]}


============================== 15:18:32.665597 | b1fda8c3-15fb-4973-955a-b208681729a6 ==============================
[0m15:18:32.665597 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:18:32.667611 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\abhishek.karmakar_s2\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt compile', 'send_anonymous_usage_stats': 'True'}
[0m15:18:32.667611 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\abhishek.karmakar_s2\dbt-files\GitHub\assignment\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:18:32.669609 [debug] [MainThread]: Command `dbt compile` failed at 15:18:32.669609 after 0.23 seconds
[0m15:18:32.669609 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025374DB2030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025374630B60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025374C17FB0>]}
[0m15:18:32.669609 [debug] [MainThread]: Flushing usage events
[0m15:18:33.663942 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:20:02.457616 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011FA324BFE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011FA3813770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011FA3811580>]}


============================== 15:20:02.467893 | 6b2bf3f6-736d-4890-b995-25ed360be834 ==============================
[0m15:20:02.467893 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:20:02.467893 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\abhishek.karmakar_s2\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:20:02.499460 [info ] [MainThread]: dbt version: 1.9.4
[0m15:20:02.499460 [info ] [MainThread]: python version: 3.12.10
[0m15:20:02.501588 [info ] [MainThread]: python path: C:\Users\abhishek.karmakar_s2\dbt-files\dbt-env\Scripts\python.exe
[0m15:20:02.501588 [info ] [MainThread]: os info: Windows-11-10.0.26100-SP0
[0m15:20:02.599529 [info ] [MainThread]: Using profiles dir at C:\Users\abhishek.karmakar_s2\.dbt
[0m15:20:02.600582 [info ] [MainThread]: Using profiles.yml file at C:\Users\abhishek.karmakar_s2\.dbt\profiles.yml
[0m15:20:02.601634 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\abhishek.karmakar_s2\dbt-files\GitHub\assignment\dbt_project.yml
[0m15:20:02.601634 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m15:20:02.604262 [debug] [MainThread]: Command `dbt debug` failed at 15:20:02.604262 after 0.40 seconds
[0m15:20:02.604262 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011FA06D84D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011FA37EECC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000011FA3372C00>]}
[0m15:20:02.604262 [debug] [MainThread]: Flushing usage events
[0m15:20:03.745645 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:45:26.129701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2C8613EF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2C8610440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2C86109E0>]}


============================== 15:45:26.137327 | 2aca5511-36af-49da-8c1c-8281a4c042de ==============================
[0m15:45:26.137327 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:45:26.139341 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\abhishek.karmakar_s2\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt clean', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:45:26.139341 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\abhishek.karmakar_s2\dbt-files\GitHub\assignment\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:45:26.142684 [debug] [MainThread]: Command `dbt clean` failed at 15:45:26.142684 after 0.25 seconds
[0m15:45:26.142684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2C8643A70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2C8020470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B2C8613DA0>]}
[0m15:45:26.142684 [debug] [MainThread]: Flushing usage events
[0m15:45:27.318223 [debug] [MainThread]: An error was encountered while trying to flush usage events
